name: trigger-replace-links

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace Repository Name
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "ProjectPythia/cookbook-template"
          replace: ${{ github.repository_owner }}/${{ github.event.repository.name }}
          regex: false

      - name: Find and Replace Repository ID
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "475509405"
          replace: ${{ github.repository_id}}
          regex: false
          
      - name: Display modified files with repo name
        run: |
          echo "Modified files: ${{ steps.find-replace-name.outputs.modifiedFiles }}"

      - name: Display modified files with repo ID
        run: |
          echo "Replaced repository ID: ${{ steps.find-replace-id.outputs.modifiedFiles }}"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
