name: trigger-replace-links

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace Repository Name
        uses: mad9000/actions-find-and-replace-string@3
        with:
          source: ${{ github.ref }}
          find: ProjectPythia/cookbook-template
          replace: ${{ github.repository_owner }}/${{ github.event.repository.name }}

      - name: Display Modified Repository Name files
        run: |
          echo "Modified files: ${{ steps.find-replace-name.outputs.modifiedFiles }}"

      - name: Find and Replace Repository ID
        uses: flcdrg/replace-multiple-action@v1
        with:
          files: "./*.md"
          find: '[{ "find": "ProjectPythia/cookbook-template", "replace": "${{ github.repository_owner }}/${{ github.event.repository.name }}" }, {"find": 475509405", "replace": "${{ github.repository_id}}"}]'

      - name: Display Modified Repository ID Files
        run: |
          echo "Replaced repository ID: ${{ steps.find-replace-id.outputs.modifiedFiles }}"

      - name: Push changes
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add -a
          git commit -m "Replacing cookbook-template links"
          git push
