name: trigger-replace-links

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Find and Replace Template Links
        uses: flcdrg/replace-multiple-action@v1
        with:
          files: "./*.md"
          find: >
            [{ "find": "ProjectPythia/cookbook-template", "replace": "${{ github.repository_owner }}/${{ github.event.repository.name }}" },
              { "find": "475509405", "replace": "${{ github.repository_id }}" }]
          encoding: utf-8

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
