name: trigger-replace-links
on:
 workflow-dispatch

 jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace Repository Name
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "ProjectPythia/cookbook-template"
          replace: ${{ github.repository_owner }}/${{ github.event.repository.name }}
          regex: false

      - name: Find and Replace Repository ID
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "475509405"
          replace: ${{ github.repository_id}}
          regex: false
