name: trigger-replace-links

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace Repository Links
        uses: flcdrg/replace-multiple-action@v1
        with:
          files: "./*.md"
          find: '[{ "find": "ProjectPythia/cookbook-template", "replace": "jukent/draft-cookbook" }, { "find": "475509405", "replace": "657326921" }]'

      - name: Push changes
        run: |
          git add -a
          git commit -m "Replacing cookbook-template links"
          git push
